[package]
name = "plugin-template"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
strip = true
opt-level = 3

[dependencies]
futures = "0.3"
plugind-core = { git = "https://github.com/viniciusfonseca/plugind" }

[lib]
crate-type = ["cdylib"]